insert into user_roles (user_role_name, access_users_read, access_users_write, access_catalogue_read, access_catalogue_write, access_inventory_read, access_inventory_write, access_orders_read, access_orders_write, access_gradings_read, access_gradings_write) values('admin', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1);
insert into user_roles (user_role_name, access_users_read, access_users_write, access_catalogue_read, access_catalogue_write, access_inventory_read, access_inventory_write, access_orders_read, access_orders_write, access_gradings_read, access_gradings_write) values('produksi', 0, 0, 1, 0, 1, 0, 1, 1, 1, 1);
insert into user_roles (user_role_name, access_users_read, access_users_write, access_catalogue_read, access_catalogue_write, access_inventory_read, access_inventory_write, access_orders_read, access_orders_write, access_gradings_read, access_gradings_write) values('gudang', 0, 0, 1, 1, 1, 1, 0, 0, 1, 0);
insert into user_roles (user_role_name, access_users_read, access_users_write, access_catalogue_read, access_catalogue_write, access_inventory_read, access_inventory_write, access_orders_read, access_orders_write, access_gradings_read, access_gradings_write) values('pelanggan', 1, 1, 1, 1, 1, 1, 1, 1, 1, 0);

insert into users (username, password, user_role_name) values('medina', '$2b$10$cJjniQOaHwsYgItJrrNfpu8TpNtnh8mkknXw9eLd8HNIaPNuRYCGu', 'admin');
insert into users (username, password, user_role_name) values('jaya', '$2b$10$Sj/TjHGpfqk3zZoYGEm.0uo4wnnowx4uYJGqxR3cxIP8JTQq7XfdC', 'produksi');
insert into users (username, password, user_role_name) values('budi', '$2b$10$Sj/TjHGpfqk3zZoYGEm.0uo4wnnowx4uYJGqxR3cxIP8JTQq7XfdC', 'gudang');
insert into users (username, password, user_role_name) values('fuad', '$2b$10$Sj/TjHGpfqk3zZoYGEm.0uo4wnnowx4uYJGqxR3cxIP8JTQq7XfdC', 'pelanggan');
